[package]
name = "sp-runner"
version = "0.1.0"
authors = ["Kristofer Bengtsson <kristofer@sekvensa.se>"]
edition = "2018"

[dependencies]
tokio = "0.1"
futures = "0.1"
uuid = { version = "0.7", features = ["serde", "v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.1"
petgraph = "0.4.13"

[dependencies.sp-domain]
path = "../sp-domain/"