[package]
name = "sp-domain"
version = "0.1.0"
authors = ["Kristofer Bengtsson <kristofer.bengtsson@chalmers.se>"]
edition = "2018"

[dependencies]
uuid = { version = "0.7.4", features = ["serde", "v4"] }
nom = "^4.2"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0.39"