[package]
name = "sp-runner-api"
version = "0.1.0"
authors = ["Martin Dahl <martin.dahl@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sp-domain = { path = "../sp-domain/" }
failure = "0.1.5"
failure_derive = "0.1.5"
