[package]
name = "control_box_simulator_rust"
version = "0.1.0"
authors = ["Martin Dahl <martin.dahl@gmail.com>"]
edition = "2018"

[dependencies]
r2r = { git = "https://github.com/sequenceplanner/r2r" }
failure = "0.1.5"
serde_json = "1.0"

[workspace]
