[package]
name = "sp-smt"
version = "0.1.0"
authors = ["Kristofer Bengtsson <kristofer.bengtsson@chalmers.se>"]
edition = "2018"

[dependencies]
env_logger = "0.6.2"
log = "0.4.8"
z3-sys = "0.5.0"
itertools = "0.8.1"
lazy_static = "1.4.0"
