[package]
name = "sp"
version = "0.5.0"
authors = ["Martin Dahl <martin.dahl@gmail.com>"]
edition = "2018"

[features]
default = ["ros"]
ros = ["sp-runner/ros"]

[dependencies]
tokio = { version = "1.9", features = ["full"] }
sp-domain = { path = "../sp-domain" }
sp-runner = { path = "../sp-runner" }