#!/bin/bash

# Put in your Rust repository's .git/hooks/pre-commit to ensure you never
# breaks rustfmt.
#
# WARNING: rustfmt is a fast moving target so ensure you have the version that
#          all contributors have.

for FILE in `git diff --cached --name-only`; do
    if [[ $FILE == *.rs ]] && [ -f $FILE ] && ! rustup run nightly rustfmt --unstable-features --skip-children --check $FILE; then
        echo "Commit rejected due to invalid formatting of \"$FILE\" file."

        exit 1
    fi
done
