import os
from glob import glob
from setuptools import setup

package_name = 'ros2_mecademic_utilities'

setup(
    name=package_name,
    version='0.0.1',
    packages=[package_name],
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        
	('share/' + package_name + '/poses/', glob('poses/*')),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    author='endree',
    author_email='',
    maintainer='endree',
    maintainer_email='',
    keywords=['ROS2'],
    classifiers=[
        'Intended Audience :: Developers',
        'Programming Language :: Python',
        'Topic :: Software Development',
    ],
    description='Autogenerated ROS2 package',
    license='',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            'ros2_mecademic_utilities = ros2_mecademic_utilities.ros2_mecademic_utilities:main',
        ],
    },
)
