import os
from glob import glob
from setuptools import setup

package_name = 'sp_dummy_r1_r2_interfacer'

setup(
    name=package_name,
    version='0.0.1',
    packages=[],
    py_modules=[
        'src.interfacer',
        'src.r1_interfacer',
        'src.r2_interfacer',
    ],
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        (os.path.join('share', package_name), glob('launch/*.launch.py')),
        ('share/' + package_name, ['package.xml']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    author='RandomName',
    author_email='',
    maintainer='RandomName',
    maintainer_email='',
    keywords=['ROS2'],
    classifiers=[
        'Intended Audience :: Developers',
        'Programming Language :: Python',
        'Topic :: Software Development',
    ],
    description='Autogenerated ROS2 package',
    license='',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
                'r1_interfacer = src.r1_interfacer:main',
                'r2_interfacer = src.r2_interfacer:main',
        ],
    },
)
